name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: |
          zip -r youtube-title-hider.zip manifest.json content.js popup.html popup.js

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: youtube-title-hider.zip
          draft: false
          prerelease: false
